### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by roryk** [wghost/UPKUtils#3]
Hi @wghost,

I'm not sure how to go about getting everything statically linked:

```
rory@clotho:build (master)$ otool -L PatchUPK
PatchUPK:
	/usr/local/lib/gcc/4.9/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.20.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/local/lib/gcc/4.9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

OSX doesn't ship with gcc, you have to install it via homebrew, so that's another difficulty for shipping a binary. I know there are ways to do it but I've never done it.

**Comment by wghost** [comment]
Try clang again. There was indeed a piece of code that behaved differently under gcc and clang and I believe I fixed it: https://github.com/wghost/UPKUtils/pull/2

**Comment by roryk** [comment]
https://dl.dropboxusercontent.com/u/2822886/UPKUtils-osx-bin.tar

**Comment by roryk** [comment]
Thanks @wghost! I'll close this issue, if you push some fixes and want them recompiled, ping me with a @roryk on the issue and I'll recompile them and update the archive.

**Comment by wghost** [comment]
@roryk
I have just updated PatcherGUI and PatchUPK project with cross-platform compatibility. I have tested it under Linux and it appears to work as intended. I'd appreciate it if you test the new code under Mac.
