### ISSUE TITLE
Does not compile on Ubuntu 12.04 (requires newer g++ and wxgtk)

### ISSUE THREAD

**Issue by MestreLion** [wghost/UPKUtils#5]
First of all, congratulations for this amazing project, as well as you other XCOM-related ones. As others have said in the nexus mods forum, you're a true pillar of the modding community, and for a good reason!

For those of us still using Ubuntu 12.04 (hey, it's supported until 2017!), UPKUtils presents 2 issues:
- `-std=c++11` flag in `build/CMakeLists.txt` was only introduced in g++ v4.8, and Ubuntu 12.04 has only up to g++ v4.6 in the repositories.
- wxGTK v.2.9 is also not available, only up to v2.8

The first has an easy fix: replace `-std=c++11` with `-std=c++0x`, or remove the flag and let the default apply, and it compiles just fine.

The second is not so trivial: as you've written somewhere, the API for dealing with strings have changed in wx2.9, so trying to use wx2.8 does not work, you code really requires 2.9+. However, there is a "semi-official" wx repository to install up to wx3.0.2 on several releases (3.0 for Ubuntu 12.04). I've tried and it works great. The steps I've created for 3.0 are:

<pre>
release=$(lsb_release -c | cut -f2)
url=http://repos.codelite.org
sudo apt-key adv --fetch-keys "$url"/CodeLite.asc
sudo apt-add-repository "deb $url/wx3.0/ubuntu/ $release universe"
sudo apt-get update
sudo apt-get install libwxgtk3.0-dev
</pre>

This way I was able to compile UPKUtils in Ubuntu 12.04 with no errors or warnings :)

It would be nice if `CMakeLists.txt` could be changed to accommodate for older distros. Can the g++ flag be changed (or removed)? Is there any reason to require the latest C11 standard? Also, maybe the test for wxgtk could check the version, and disable wx if < 2.9. In any case, the instructions for installing wx3.0 could be useful to be included somewhere (README.md perhaps?)

Thanks!

**Comment by MestreLion** [comment]
Some more info:
- That wx repository is actually official (or at least officially endorsed), as it's mentioned at https://www.wxwidgets.org/downloads/
- The steps I've mentioned are derived from http://codelite.org/LiteEditor/OlderWxWidgetsBinaries

**Comment by wghost** [comment]
I use these versions of g++ and wxgtk for my work, so it's easier for me to stick to them.

I don't know about Ubuntu, but other distributions usually get kernel and g++ updates very often. And c++ 11 is old already :) c++ 14 is the new one :)
