### ISSUE TITLE
Support UPK versions higher than 845

### ISSUE THREAD

**Issue by krozett** [wghost/UPKUtils#6]
I've used these tools on the Goat Simulator packages, which are all version 868, and they work just fine. I had to disable the version check, however.

IMO this version check should simply be a warning (that the input file may be unsupported), rather than cause the tools to simply not run.

**Comment by wghost** [comment]
Version number usually changes along with serialization code, plus, I never tested the tool for games other than XCOM and Firaxis reworked the engine considerably as they themselves say. So I decided that checking for the exact version will be safer. Good to know that the tool works for Goat Simulator, though. :)

**Comment by Patola** [comment]
Are these tools meant to work on XCOM: UE (2012) savegames from Linux? I have tried them but only got error messages, be it from the packed or unpacked files (via xcom.exe decompressor run via wine):

```
[2:26] [3439] [patola@ovo build]% ./ExtractNameLists save36-packed.upk 
ExtractNameLists
Error reading package:
Bad package signature!
[2:26] [3440] [patola@ovo build]% ./ExtractNameLists save36-unpacked.upk
ExtractNameLists
Error reading package:
Bad package signature!
[2:27] [3441] [patola@ovo build]% ./CompareUPK save36-packed.upk save36-packed.upk 
CompareUPK
Error reading package: save36-packed.upk
Bad package signature!
[2:27] [3442] [patola@ovo build]% ./CompareUPK save36-unpacked.upk save36-unpacked.upk 
CompareUPK
Error reading package: save36-unpacked.upk
Bad package signature!
```

**Comment by wghost** [comment]
Save games have different data structure, so UPK tools can't read them.
