### ISSUE TITLE
UPK filename converted to lower case?

### ISSUE THREAD

**Issue by shaygover** [wghost/UPKUtils#7]
Hi,

I'm trying to use PatcherGUI and UPKUtils to pacth the linux version of XCOM. Patching works only if I rename the UPK files to lower case. For example:
UICollection_Strategy_SF.upk to uicollection_strategy_sf.upk

Can you help me locate the right function?

Thanks

**Comment by wghost** [comment]
std::transform(UPKFileName.begin(), UPKFileName.end(), UPKFileName.begin(), ::tolower);

I don't remember, but aren't upk files in lowercase for Linux version of the game? That line was added for a reason.

**Comment by shaygover** [comment]
No. The aren't. Maybe in earlier versions.

**Comment by shaygover** [comment]
Interesting, just reinstalled and files went lowercase... 
Closing
